$(document).ready(function(){
    $('#modal-btn').click(function(){
        console.log('Funcionando')
        $('.ui.modal')
        .modal('show')
        ;
    })
    $('.ui.dropdown').dropdown()
})